services:
  grafana:
    image: grafana/grafana:10.2.4-ubuntu
    container_name: monitor-grafana
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/provisioning/dashboards/:/etc/grafana/provisioning/dashboards/
      - ./config/provisioning/datasources/:/etc/grafana/provisioning/datasources/
      - ./config/grafana/dashboards/:/var/lib/grafana/dashboards/
      - ./config/grafana/plugins/:/var/lib/grafana/plugins/
    networks:
      - dibimbing

networks:
  dibimbing:
    external: true

volumes:
  grafana_data: